language: node_js
cache:
  directories:
    - $HOME/.npm
notifications:
  email:
    on_failure: always
install:
node_js:
  - "10"
script:
  - npm run lint
  - npm test
  - npx codecov
deploy:
  skip_cleanup: true
  provider: script
  script:
    - pip install --user awscli aws-sam-cli
    - npm run deploy
  on:
    branch: master
after_success:
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
