language: node_js
cache:
  directories:
    - $HOME/.npm
notifications:
  email:
    on_failure: always
install:
  - npm install
  - pip install --user awscli
  - pip install --user aws-sam-cli
node_js:
  - "10"
  - "9"
  - "8"
script:
  - npm run lint
  - npm test
  - npx codecov
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
  - npm run deploy
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
