language: node_js
cache:
  directories:
    - $HOME/.npm
notifications:
  email:
    on_failure: always
install:
  - npm install
  - pip install --user awscli
  - pip install --user aws-sam-cli
node_js:
  - "8.10"
script:
  - npm run lint
  - npm test
  - npx codecov
after_success:
  - npx semantic_release
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
