language: node_js
notifications:
  email:
    on_failure: always
node_js:
  - "10"
script:
  - npm run lint
  - npm test
  - npx codecov
before_deploy:
  - pip install --user awscli aws-sam-cli
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master
after_success:
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
