AWSTemplateFormatVersion: "2010-09-09"
Description:
  JSON API para consultar la Tasa Representativa del Mercado en la Superintendencia
  Financiera de Colombia.
Outputs:
  ApiUrl:
    Description: Endpoint de API Gateway
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  DateApi:
    Description: "Funci\xC3\xB3n Lambda"
    Value:
      Ref: DateApi
  TrmTable:
    Description: Tabla de DynamoDB
    Value:
      Ref: TrmTable
Resources:
  DateApi:
    Properties:
      CodeUri: s3://trmapi/56e52a9ac3afe7226ce236ced27c5bd4
      Description:
        "Consulta el servicio web de la SFC y devuelve la informaci\xC3\
        \xB3n en formato JSON."
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TrmTable
      Events:
        date:
          Properties:
            Method: GET
            Path: /{date}
          Type: Api
        latest:
          Properties:
            Method: GET
            Path: /latest
          Type: Api
        timeseries:
          Properties:
            Method: GET
            Path: /timeseries
          Type: Api
      Handler: handler.trm
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Ref: TrmTable
      Runtime: nodejs8.10
      Tags:
        AppName:
          Ref: AWS::StackName
      Timeout: 5
    Type: AWS::Serverless::Function
  TrmTable:
    Properties:
      AttributeDefinitions:
        - AttributeName: partition
          AttributeType: N
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: partition
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      Tags:
        - Key: AppName
          Value:
            Ref: AWS::StackName
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
